# Load dataset

In [4]:
import pandas as pd

pd.set_option("display.max_columns", None)

file_id = "1jVzIRp6zxrGVDXRtuG-8mc6CzHrbQFED"
url = f"https://drive.google.com/uc?export=download&id={file_id}"

df = pd.read_csv(
    url,
    parse_dates=["started_at"],
    dtype={"y_overdue": "boolean", "prev_late": "boolean"},
)
df.head()

,id,started_at,customer_id,client_id,tenant,hour,dow,month,is_weekend,plan_hours,n_batteries,model,deposit_kind,deposit_amount,price_total,prepaid_share,client_residency,block_missing,issued_by_employee_id,first_visit,client_prev_rentals,client_prev_late_rate,client_prev_lost,prev_late,days_since_prev,y_overdue,y_lost
0,65f0da3c-7abb-4f9c-b2b7-1968b8a663e2,2025-01-18 12:19:51+00:00,2975e970-5ed2-46f0-b809-f455e9873912,01d32244-c1b4-4a1a-97c1-b414ab17aa69,synth-a,15,5,1,True,72.000000,1,Trail 350,document,NaN,5720.0,0.0,local,False,23b8c1e9-3924-46de-beb1-3b9046685257,True,0,NaN,0,<NA>,NaN,False,False
1,9dddd117-7806-49e8-9857-f0891492517a,2025-01-18 13:01:54+00:00,e5ceac23-aff7-488d-aada-d07f2d6b89e7,662e7ea7-9c74-4faf-8fed-aa3b52e3b310,synth-a,16,5,1,True,2.000000,2,Cargo 500,cash,2000.0,870.0,0.0,local,False,17fc695a-07a0-4a6e-8822-e8f36c031199,False,2,NaN,0,<NA>,7.291227,False,False
2,5f2c2c26-7b12-4db4-a509-1af3c7a9b788,2025-01-18 14:32:11+00:00,3bd8a8e5-feaf-47c1-9ff9-6ac8294b1d6f,53028b18-d032-4689-8dd3-b231402c1e98,synth-a,17,5,1,True,2.000000,1,Cargo 500,document,NaN,NaN,NaN,local,False,8fadc1a6-06cb-4fb3-9a1d-e644815ef6d1,False,1,NaN,0,<NA>,19.314884,False,False
3,e9a9ea82-7552-46e3-abd2-277e49bae976,2025-01-18 14:58:59+00:00,ef4e31fe-b93b-4061-95bd-125ecfdc8f7b,918eade9-dbd4-44b9-89d6-158602d45aad,synth-c,16,5,1,True,4.016944,2,Cargo 500,NaN,NaN,NaN,NaN,NaN,True,6e996e3e-e3b1-47fc-8a34-50fc9918ee46,True,0,NaN,0,<NA>,NaN,False,False
4,2a036585-d898-484e-834d-216eb0b615c0,2025-01-18 15:12:19+00:00,d3497354-5320-4fc3-9f36-8a17065f8f69,7626e160-db24-44cb-85aa-e5ca667d6f8e,synth-b,20,5,1,True,0.794722,1,Urban 250,NaN,NaN,NaN,NaN,NaN,True,50f0fd0a-750c-4b75-8ccc-9bc2a53f8a28,True,0,NaN,0,<NA>,NaN,True,False

# EDA

In [8]:
df.describe()

,hour,dow,month,plan_hours,n_batteries,deposit_amount,price_total,prepaid_share,client_prev_rentals,client_prev_late_rate,client_prev_lost,days_since_prev
count,39344.000000,39344.000000,39344.000000,39344.000000,39344.000000,6836.00000,21490.000000,19358.000000,39344.000000,23384.000000,39344.0,23711.000000
mean,12.291734,3.126703,6.571421,21.580956,1.303070,2727.61849,2245.196370,0.549799,2.110436,0.082659,0.0,13.401769
std,3.328721,2.028164,2.813368,38.387186,0.459591,1461.76961,2774.688965,0.445396,2.877998,0.208218,0.0,12.748747
min,9.000000,0.000000,1.000000,0.002778,1.000000,1000.00000,270.000000,0.000000,0.000000,0.000000,0.0,0.296829
25%,9.000000,1.000000,5.000000,2.000000,1.000000,2000.00000,890.000000,0.000000,0.000000,0.000000,0.0,5.623547
50%,12.000000,3.000000,7.000000,4.000000,1.000000,2000.00000,1440.000000,0.500000,1.000000,0.000000,0.0,9.817512
75%,15.000000,5.000000,9.000000,24.000000,2.000000,3000.00000,2210.000000,1.000000,3.000000,0.000000,0.0,16.937859
max,20.000000,6.000000,12.000000,168.000000,2.000000,5000.00000,17320.000000,1.000000,26.000000,1.000000,0.0,315.135579